### ISSUE TITLE
please remove postinstall

### ISSUE THREAD

**Issue by bgold0** [michal-wrzosek/apollo-boost-upload#1]
Michal! Thanks for making this repo. It work's perfectly. Only problem is the postinstall script really screws with our CI because now we have to do `npm install --ignore-scripts`. Anyway you can remove that postinstall because it's not really needed to actually use this package.

**Comment by michal-wrzosek** [comment]
Hi @bgold0 ! Thanks a lot for pointing out this bug. I fixed it and pushed it with v1.0.1. Let me know if something is still wrong.
